CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR,
    PICTURE VARCHAR
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR
);

INSERT INTO ROLES(ID,NAME) VALUES(1,'ROLE_ADMIN'),(2,'ROLE_USER');

CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR,
    SURNAME VARCHAR,
    EMAIL VARCHAR,
    PASSWORD VARCHAR,
    PICTURE VARCHAR
);

CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    USER_ID BIGINT REFERENCES USERS(ID),
    ROLES_ID BIGINT REFERENCES ROLES(ID)
    );

INSERT INTO USERS_ROLES(USER_ID,ROLES_ID) VALUES (1,1);

CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR,
    DESCRIPTION VARCHAR,
    PRICE BIGINT,
    QUANTITY INT,
    PICTURE VARCHAR,
    CATEGORY_ID BIGINT REFERENCES CATEGORIES(ID)
    );

CREATE TABLE IF NOT EXISTS FEATURES
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS PRODUCTS_FEATURES
(
    PRODUCT_ID BIGINT REFERENCES PRODUCTS(ID),
    FEATURES_ID BIGINT REFERENCES FEATURES(ID)
    );

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    COMMENT VARCHAR,
    DATE DATE,
    RATE INT,
    PRODUCT_ID BIGINT REFERENCES PRODUCTS(ID),
    USER_ID BIGINT REFERENCES USERS(ID)
    );

CREATE TABLE IF NOT EXISTS ORDERITEMS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    PRODUCT_ID BIGINT REFERENCES PRODUCTS(ID),
    QUANTITY INT
    );

CREATE TABLE IF NOT EXISTS ORDERS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    USER_ID BIGINT REFERENCES USERS(ID),
    DATE_TIME TIMESTAMP,
    ORDER_STATUS SMALLINT
    );

CREATE TABLE IF NOT EXISTS ORDERS_ORDER_ITEMS
(
    ORDER_ID BIGINT REFERENCES ORDERS(ID),
    ORDER_ITEMS_ID BIGINT REFERENCES ORDERITEMS(ID)
    );

CREATE TABLE IF NOT EXISTS USERS_ORDERS
(
    USER_ID BIGINT REFERENCES USERS(ID),
    ORDERS_ID BIGINT REFERENCES ORDERS(ID)
    );